pipeline:
  clone:
    image: plugins/git
    depth: 1

  test:
    image: python:3.7-alpine
    commands:
      - pip install -r requirements/ci.txt
      - flake8 .
      - py.test service_builder/tests
    when:
      event: [pull_request, push, tag]
