version: "3.6"

services:
  django_service_wizard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_service_wizard
    image: django_service_wizard
    volumes:
      - .:/code
