services:
  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db

pipeline:
  test:
    image: python:3.7
    commands:
      - bash scripts/tcp-port-wait.sh $${DATABASE_HOST} $${DATABASE_PORT}
      - bash scripts/run-tests.sh --ci
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    when:
      event: [pull_request, push, tag]
