version: "3.1"

services:

  postgres_{{ name_project }}:
    container_name: postgres_{{ name_project }}
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4-alpine
    env_file: .env
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  {{ name_project }}:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint-dev.sh
    container_name: {{ name_project }}
    image: {{ name_project }}
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres_{{ name_project }}
    env_file: .env
    environment:
      JWT_PUBLIC_KEY_RSA_BIFROST: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
