version: "3.1"

services:

  postgres_{{ name_project }}:
    container_name: postgres_{{ name_project }}
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4
    environment:
      POSTGRES_DB: {{ name_project }}
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  {{ name_project }}:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - environment=localhost
    container_name: {{ name_project }}
    image: {{ name_project }}
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres_{{ name_project }}
    environment:
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "{{ name_project }}"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_{{ name_project }}"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      JWT_PUBLIC_KEY_RSA_ACTIVITYAPI: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
