version: "3.1"

services:
  postgres_sayhello_service:
    env_file:
      - .env
    container_name: postgres_sayhello_service
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4-alpine
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  sayhello_service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint-dev.sh
    container_name: sayhello_service
    image: sayhello_service
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - postgres_sayhello_service
    environment:
      JWT_PUBLIC_KEY_RSA_BIFROST: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
